// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCks-lqEQMtrY53Z8U5MGMN0eC5CtuPCew',
    appId: '1:402888703568:web:57b0bc5089fc2464909b55',
    messagingSenderId: '402888703568',
    projectId: 'pit-report',
    authDomain: 'pit-report.firebaseapp.com',
    databaseURL: 'https://pit-report-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pit-report.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZHa584oDWakPOCn_-bErZ_lgBbgy_78g',
    appId: '1:402888703568:android:e9c105dd73839db5909b55',
    messagingSenderId: '402888703568',
    projectId: 'pit-report',
    databaseURL: 'https://pit-report-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pit-report.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyLQoWFFIXVIjfTIGxS2Svq7PUCh3Yodw',
    appId: '1:402888703568:ios:b0517167294661fe909b55',
    messagingSenderId: '402888703568',
    projectId: 'pit-report',
    databaseURL: 'https://pit-report-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pit-report.firebasestorage.app',
    iosBundleId: 'com.example.pitreport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyLQoWFFIXVIjfTIGxS2Svq7PUCh3Yodw',
    appId: '1:402888703568:ios:b0517167294661fe909b55',
    messagingSenderId: '402888703568',
    projectId: 'pit-report',
    databaseURL: 'https://pit-report-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pit-report.firebasestorage.app',
    iosBundleId: 'com.example.pitreport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCks-lqEQMtrY53Z8U5MGMN0eC5CtuPCew',
    appId: '1:402888703568:web:6762d0eb419389d1909b55',
    messagingSenderId: '402888703568',
    projectId: 'pit-report',
    authDomain: 'pit-report.firebaseapp.com',
    databaseURL: 'https://pit-report-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pit-report.firebasestorage.app',
  );
}
